const PRESETS=[['classic','经典清晰','细线分组 · 信息紧凑'],['modern','现代专业','深色抬头 · 时间线条目'],['editorial','侧标叙事','左侧分组 · 右侧经历'],['minimal','留白极简','居中抬头 · 轻量分隔'],['executive','沉稳商务','顶部色条 · 加粗层次'],['compact','高效紧凑','缩减间隔 · 提升信息密度'],['academic','学术书卷','宋体正文 · 居中章节'],['custom','自定义排版','自由拖动 · 八向缩放 · 跨页移动']];
const MM=96/25.4;let selectedBlock=null,customClean=false,dragState=null,undoStack=[],redoStack=[];
function validateLayout(d){
 const c=d.settings.custom;if(c===undefined)return d;
 if(!c||!Number.isInteger(c.pages)||c.pages<1||c.pages>100||typeof c.snap!=='boolean'||!c.blocks||typeof c.blocks!=='object'||Array.isArray(c.blocks)||Object.keys(c.blocks).length>5000)throw Error('自定义排版格式不正确');
 for(const [id,r] of Object.entries(c.blocks)){if(!/^[a-zA-Z0-9_-]{1,100}$/.test(id)||!r||!['x','y','w','h','page','font'].every(k=>Number.isFinite(r[k]))||!Number.isInteger(r.page)||r.page<0||r.page>=c.pages||r.x<0||r.y<0||r.w<15||r.h<8||r.x+r.w>210.1||r.y+r.h>283.1||r.font<8||r.font>16)throw Error('模块尺寸或位置超出范围');}
 return d;
}
function ensureIds(){const seen=new Set();for(const s of data.sections)for(const i of s.items){if(typeof i.layoutId!=='string'||!/^m_[a-z0-9_-]+$/.test(i.layoutId)||seen.has(i.layoutId))i.layoutId='m_'+crypto.randomUUID().replaceAll('-','');seen.add(i.layoutId);}}
function basicCopy(){const b=data.basic;const fields=[['手机',b.phone],['邮箱',b.email]].filter(([,value])=>value.trim());return `<div class="resume-copy"><h1>${esc(b.name)}</h1>${fields.length?`<div class="contact">${fields.map(([label,value])=>`<div class="contact-field" aria-label="${label}"><span class="contact-value">${esc(value)}</span></div>`).join('')}</div>`:''}</div>`;}
heading=function(){const b=data.basic;return `<div class="resume-head">${b.photo&&b.showPhoto?`<img src="${b.photo}" alt="简历照片">`:''}${basicCopy()}</div>`;};
function modules(){ensureIds();const b=data.basic;const html=`<div class="resume-head">${basicCopy()}</div>`;
 const list=[{id:'basic',label:'基本信息',html}];if(b.photo&&b.showPhoto)list.push({id:'photo',label:'照片',html:`<img class="custom-photo" src="${b.photo}" alt="简历照片">`});
 for(const s of data.sections.filter(s=>s.enabled))for(const i of s.items){if(![i.title,i.meta,i.date,i.body].some(v=>v.trim()))continue;list.push({id:i.layoutId,label:s.title+(i.title?' · '+i.title:''),html:`<h2 class="section-title">${esc(s.title)}</h2>${itemHTML(i,i.body.split('\n').map(v=>v.trim()).filter(Boolean))}`});}return list;
}
function layoutState(){if(!data.settings.custom)data.settings.custom={pages:1,snap:true,blocks:{}};return data.settings.custom;}
function remember(){undoStack.push(clone(layoutState()));if(undoStack.length>40)undoStack.shift();redoStack=[];}
function persistLayout(){try{localStorage.setItem(KEY,JSON.stringify(data));$('#saved').textContent='排版已自动保存';}catch{$('#saved').textContent='自动保存失败，请备份内容';}}
function measureModule(m,w,font=data.settings.size){const probe=document.createElement('div');probe.className='page custom';probe.style.cssText='position:absolute;left:-10000px;top:0;visibility:hidden;zoom:1;';probe.style.setProperty('--accent',data.settings.accent);probe.style.setProperty('--font-size',data.settings.size+'pt');probe.style.setProperty('--leading',data.settings.line);probe.innerHTML=`<div class="custom-block" style="width:${w}mm;font-size:${font}pt"><div class="block-content" style="height:auto">${m.html}</div></div>`;document.body.append(probe);const h=probe.querySelector('.block-content').getBoundingClientRect().height/MM+.7;probe.remove();return Math.max(8,h);}
function syncModules(repack=false){const c=layoutState(),list=modules();if(repack){c.blocks={};c.pages=1;}let page=0,y=14;
 if(!repack){for(const r of Object.values(c.blocks)){if(r.page>page){page=r.page;y=r.y+r.h+5;}else if(r.page===page)y=Math.max(y,r.y+r.h+5);}}
 for(const m of list){if(c.blocks[m.id])continue;if(m.id==='photo'){c.blocks[m.id]={page:0,x:173,y:14,w:23,h:27,font:data.settings.size};continue;}const w=m.id==='basic'&&data.basic.showPhoto?151:182;const h=Math.min(260,Math.ceil(measureModule(m,w)*10)/10);if(y+h>277){page++;y=14;}c.blocks[m.id]={page,x:14,y,w,h,font:data.settings.size};y+=h+5;}
 c.pages=Math.max(c.pages,page+1);return list;
}
const autoDesign=design,autoRender=render;
const fullEditor=editor;
editor=function(){fullEditor();for(const k of ['gender','city','target'])document.querySelector(`[data-path="basic.${k}"]`)?.closest('label').remove();document.querySelectorAll('#content .row').forEach(row=>{if(!row.children.length)row.remove();else if(row.children.length===1)row.style.gridTemplateColumns='1fr';});};
design=function(){autoDesign();const first=$('#design p.help');first.textContent='七种排版预设，或自由设计。切换样式保留文字和自定义位置。';$('#design').querySelectorAll('.template').forEach(n=>n.remove());first.insertAdjacentHTML('afterend',PRESETS.map(([id,t,d])=>`<button class="template ${data.settings.template===id?'active':''}" data-template="${id}"><span class="mini ${id}"></span><span><strong>${t}</strong><small>${d}</small></span></button>`).join(''));
 if(data.settings.template==='custom'){$('#design > .hint').textContent='每条经历是独立模块。点击模块选中，拖动正文或顶部绿色标签移动，拖动边角调整大小。窄模块会自动换行；红框表示文字放不下。';$('#design').insertAdjacentHTML('afterbegin','<div id="custom-inspector" class="custom-inspector"></div>');inspector();}}
function inspector(){const panel=$('#custom-inspector');if(!panel)return;const c=layoutState(),list=modules(),m=list.find(m=>m.id===selectedBlock),r=c.blocks[selectedBlock];panel.innerHTML=`<h3>自由排版 <span class="custom-badge">单位：毫米</span></h3><label class="field">选择模块<select id="module-select"><option value="">点击画布上的模块</option>${list.map(m=>`<option value="${m.id}" ${m.id===selectedBlock?'selected':''}>${esc(m.label)}</option>`).join('')}</select></label>`+(m&&r?`<div class="row">${rectField('所在页','page',r.page+1,1,c.pages)}${rectField('字号（pt）','font',r.font,8,16)}</div><div class="row">${rectField('距左 X','x',r.x,0,210-r.w)}${rectField('距上 Y','y',r.y,0,283-r.h)}</div><div class="row">${rectField('宽度','w',r.w,15,210-r.x)}${rectField('高度','h',r.h,8,283-r.y)}</div><div class="controls"><button data-custom="align-left">左对齐</button><button data-custom="center">水平居中</button><button data-custom="align-right">右对齐</button><button data-custom="fit-height">适应文字高度</button></div><p class="help">选中模块后，方向键微调 1mm；Shift + 方向键移动 5mm。可拖到另一页，或修改所在页。</p>`:'<p class="help">照片、基本信息和每条经历都可以独立调整。先在右侧点击一个模块。</p>');}
function rectField(label,key,v,min,max){return `<label class="field">${label}<input type="number" data-rect="${key}" value="${Math.round(v*10)/10}" min="${min}" max="${Math.max(min,max)}" step="${key==='page'?1:.1}"></label>`;}
function applyRect(node,r){node.style.left=r.x+'mm';node.style.top=r.y+'mm';node.style.width=r.w+'mm';node.style.height=r.h+'mm';node.style.fontSize=r.font+'pt';}
function selectBlock(id,refresh=true){selectedBlock=id;document.querySelectorAll('.custom-block').forEach(n=>n.classList.toggle('selected',n.dataset.block===id));if(refresh){if($('#design').classList.contains('hidden'))document.querySelector('[data-tab="design"]').click();if(!$('#custom-inspector'))design();inspector();}}
function renderCustom(){const root=$('#pages'),list=syncModules(),c=layoutState();root.innerHTML='';root.style.setProperty('--font-size',data.settings.size+'pt');root.style.setProperty('--leading',data.settings.line);root.style.setProperty('--accent',data.settings.accent);root.classList.toggle('layout-clean',customClean);let bar=$('#custombar');if(!bar){bar=document.createElement('div');bar.id='custombar';bar.className='custombar';root.before(bar);}bar.innerHTML=`<span class="custom-help">拖动模块 · 边角缩放 · 可跨页</span><button data-custom="undo" ${undoStack.length?'':'disabled'}>↶ 撤销</button><button data-custom="redo" ${redoStack.length?'':'disabled'}>↷ 重做</button><button data-custom="add-page">＋ 新增页</button><button data-custom="remove-page">删除末尾空页</button><button data-custom="repack">自动整理</button><label><input id="snap-toggle" type="checkbox" ${c.snap?'checked':''}> 2mm 吸附</label><button data-custom="clean">${customClean?'显示编辑框':'干净预览'}</button><span class="status" id="layout-status"></span>`;
 for(let p=0;p<c.pages;p++){const page=document.createElement('article');page.className='page custom'+(c.snap?' grid-on':'');page.dataset.page=p;page.innerHTML=`<div class="safe-guide"></div><span class="custom-page-label">第 ${p+1} 页 · A4</span><footer><span>${esc(data.basic.name)}</span><span>${p+1} / ${c.pages}</span></footer>`;root.append(page);}
 for(const m of list){const r=c.blocks[m.id],node=document.createElement('div');node.className='custom-block'+(m.id===selectedBlock?' selected':'');node.dataset.block=m.id;node.tabIndex=0;node.setAttribute('aria-label',m.label+'，可拖动和调整大小');node.innerHTML=`<div class="block-grip">⠿ ${esc(m.label)}</div><div class="block-content ${m.id==='photo'?'photo-content':''}">${m.html}</div>${['nw','n','ne','e','se','s','sw','w'].map(edge=>`<span class="resize-handle" data-edge="${edge}" aria-hidden="true"></span>`).join('')}`;applyRect(node,r);root.children[r.page].append(node);}
 $('#page-count').textContent=`A4 · ${c.pages} 页 · 自定义`;fitZoom();checkLayout();inspector();}
render=function(){ensureIds();if(data.settings.template==='custom')renderCustom();else{$('#custombar')?.remove();$('#pages').classList.remove('layout-clean');autoRender();}}
function checkLayout(){let overflow=0,overlap=0;const nodes=[...document.querySelectorAll('.custom-block')],c=layoutState();for(const n of nodes){const el=n.querySelector('.block-content');const bad=el.scrollHeight>el.clientHeight+1||el.scrollWidth>el.clientWidth+1;n.classList.toggle('issue',bad);n.dataset.overflow=bad?'true':'false';if(bad)overflow++;}
 for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=c.blocks[nodes[i].dataset.block],b=c.blocks[nodes[j].dataset.block];if(a.page===b.page&&Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)>.5&&Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y)>.5)overlap++;}
 const status=$('#layout-status');if(status){status.textContent=overflow?`${overflow} 个模块文字超出边框，请放大模块、减小字号或拆分内容。`:overlap?`${overlap} 处模块相交，请检查是否遮挡文字。`:'布局检查通过 · 内容完整显示';status.classList.toggle('problem',!!(overflow||overlap));}return {overflow,overlap};}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function finishEdit(){renderCustom();persistLayout();}
document.addEventListener('input',e=>{if(e.target.dataset.path==='settings.size'&&data.settings.template==='custom'){remember();for(const r of Object.values(layoutState().blocks))r.font=Number(e.target.value);}},true);
document.addEventListener('change',e=>{if(e.target.id==='module-select'){selectBlock(e.target.value);const n=[...document.querySelectorAll('.custom-block')].find(n=>n.dataset.block===selectedBlock);n?.scrollIntoView({block:'center',behavior:'smooth'});}if(e.target.id==='snap-toggle'){remember();layoutState().snap=e.target.checked;finishEdit();}if(e.target.dataset.rect){const key=e.target.dataset.rect,r=layoutState().blocks[selectedBlock],v=Number(e.target.value);if(!r||!Number.isFinite(v)||e.target.value===''){inspector();return;}remember();if(key==='page')r.page=clamp(Math.round(v)-1,0,layoutState().pages-1);if(key==='font')r.font=clamp(v,8,16);if(key==='x')r.x=clamp(v,0,210-r.w);if(key==='y')r.y=clamp(v,0,283-r.h);if(key==='w')r.w=clamp(v,15,210-r.x);if(key==='h')r.h=clamp(v,8,283-r.y);finishEdit();}});
document.addEventListener('click',e=>{const cmd=e.target.closest('[data-custom]')?.dataset.custom;if(!cmd)return;const c=layoutState(),r=c.blocks[selectedBlock];if(cmd==='clean'){customClean=!customClean;renderCustom();return;}if(cmd==='undo'||cmd==='redo'){const from=cmd==='undo'?undoStack:redoStack,to=cmd==='undo'?redoStack:undoStack;if(!from.length)return;to.push(clone(c));data.settings.custom=from.pop();finishEdit();return;}if(cmd==='repack'&&!confirm('按当前内容重新排列全部模块？可通过撤销恢复。'))return;if(cmd==='remove-page'&&modules().some(m=>c.blocks[m.id]?.page===c.pages-1)){toast('末页还有模块，请先移到其他页。');return;}if(cmd==='remove-page'&&c.pages===1){toast('至少保留一页。');return;}if(cmd==='add-page'&&c.pages>=100){toast('最多支持 100 页。');return;}remember();if(cmd==='add-page')c.pages++;if(cmd==='remove-page'){c.pages--;for(const rect of Object.values(c.blocks))rect.page=Math.min(rect.page,c.pages-1);}if(cmd==='repack')syncModules(true);if(r){if(cmd==='align-left')r.x=14;if(cmd==='align-right')r.x=Math.max(0,196-r.w);if(cmd==='center')r.x=(210-r.w)/2;if(cmd==='fit-height'){const m=modules().find(m=>m.id===selectedBlock);if(m&&m.id!=='photo')r.h=clamp(measureModule(m,r.w,r.font),8,283-r.y);}}if(r)r.x=clamp(r.x,0,210-r.w);finishEdit();});
// Pointer capture keeps drags stable when the cursor leaves a block or scrolls to another page.
document.addEventListener('pointerdown',e=>{const node=e.target.closest('.custom-block');if(!node||customClean||e.button!==0)return;e.preventDefault();selectBlock(node.dataset.block);node.focus({preventScroll:true});const r=layoutState().blocks[selectedBlock];dragState={node,id:selectedBlock,start:clone(r),before:clone(layoutState()),edge:e.target.dataset.edge||'',clientX:e.clientX,clientY:e.clientY,startX:e.clientX,startY:e.clientY,pointer:e.pointerId,moved:false};const box=node.parentElement.getBoundingClientRect();dragState.anchorX=(e.clientX-box.left)/box.width*210-r.x;dragState.anchorY=(e.clientY-box.top)/box.height*297-r.y;node.setPointerCapture(e.pointerId);node.dataset.dragging='';dragState.raf=requestAnimationFrame(dragTick);});
document.addEventListener('pointermove',e=>{if(!dragState||e.pointerId!==dragState.pointer)return;dragState.clientX=e.clientX;dragState.clientY=e.clientY;dragMove();});
function dragMove(){const d=dragState;if(!d)return;const c=layoutState(),r=c.blocks[d.id],s=d.start,snap=v=>c.snap?Math.round(v/2)*2:v;d.moved=d.moved||Math.abs(d.clientX-d.startX)+Math.abs(d.clientY-d.startY)>3;if(!d.moved)return;
 const pages=[...document.querySelectorAll('.page.custom')];if(!d.edge){const target=pages.find(p=>{const b=p.getBoundingClientRect();return d.clientY>=b.top&&d.clientY<=b.bottom;})||pages[r.page];const b=target.getBoundingClientRect();r.page=Number(target.dataset.page);r.x=clamp(snap((d.clientX-b.left)/b.width*210-d.anchorX),0,210-r.w);r.y=clamp(snap((d.clientY-b.top)/b.height*297-d.anchorY),0,283-r.h);if(d.node.parentElement!==target)target.append(d.node);}else{const b=pages[s.page].getBoundingClientRect(),dx=(d.clientX-d.startX)/b.width*210,dy=(d.clientY-d.startY)/b.height*297;if(d.edge.includes('e'))r.w=clamp(snap(s.w+dx),15,210-s.x);if(d.edge.includes('s'))r.h=clamp(snap(s.h+dy),8,283-s.y);if(d.edge.includes('w')){r.x=clamp(snap(s.x+dx),0,s.x+s.w-15);r.w=s.x+s.w-r.x;}if(d.edge.includes('n')){r.y=clamp(snap(s.y+dy),0,s.y+s.h-8);r.h=s.y+s.h-r.y;}}applyRect(d.node,r);checkLayout();}
function dragTick(){if(!dragState)return;const stage=$('.stage'),b=stage.getBoundingClientRect(),y=dragState.clientY;let speed=y>b.bottom-60?12:y<b.top+60?-12:0;if(speed){stage.scrollTop+=speed;dragMove();}dragState.raf=requestAnimationFrame(dragTick);}
function endDrag(e,cancel=false){const d=dragState;if(!d||e.pointerId!==d.pointer)return;cancelAnimationFrame(d.raf);dragState=null;d.node.removeAttribute('data-dragging');if(d.node.hasPointerCapture(e.pointerId))d.node.releasePointerCapture(e.pointerId);if(cancel)data.settings.custom=d.before;else if(d.moved){undoStack.push(d.before);if(undoStack.length>40)undoStack.shift();redoStack=[];}renderCustom();persistLayout();}
document.addEventListener('pointerup',e=>endDrag(e));document.addEventListener('pointercancel',e=>endDrag(e,true));
document.addEventListener('keydown',e=>{if(data.settings.template!=='custom'||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||customClean)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();document.querySelector(`[data-custom="${e.shiftKey?'redo':'undo'}"]`)?.click();return;}const r=layoutState().blocks[selectedBlock];if(!r||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();remember();const step=e.shiftKey?5:1;r.x=clamp(r.x+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0),0,210-r.w);r.y=clamp(r.y+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0),0,283-r.h);finishEdit();});
function exportReady(){if(data.settings.template!=='custom')return true;const issues=checkLayout();if(issues.overflow){toast('有模块文字未完整显示，请先调整红框模块再导出。');return false;}if(issues.overlap&&!confirm('模块之间有重叠，请确认预览没有文字遮挡。仍要导出吗？'))return false;return true;}
$('#export').onclick=()=>{if(exportReady())$('#print-dialog').showModal();};$('#confirm-print').onclick=()=>{if(!exportReady())return;$('#print-dialog').close();document.title=(data.basic.name||'我的')+'的简历';render();setTimeout(()=>window.print(),150);};
